FROM python:3.6-alpine
RUN apk add --update build-base libffi-dev
RUN apk add --update postgresql-dev
RUN pip install gunicorn gevent
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD exec gunicorn --bind :$PORT -k gevent --workers 2 weather:app
